/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spring_java8_nativefunction_test1_HelloNative */

#ifndef _Included_com_spring_java8_nativefunction_test1_HelloNative
#define _Included_com_spring_java8_nativefunction_test1_HelloNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spring_java8_nativefunction_test1_HelloNative
 * Method:    greeting
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_spring_java8_nativefunction_test1_HelloNative_greeting
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
