/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spring_java8_nativefunction_test4_Employee */

#ifndef _Included_com_spring_java8_nativefunction_test4_Employee
#define _Included_com_spring_java8_nativefunction_test4_Employee
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spring_java8_nativefunction_test4_Employee
 * Method:    raiseSalary
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_spring_java8_nativefunction_test4_Employee_raiseSalary
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
