/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spring_java8_nativefunction_test2_Printf1 */

#ifndef _Included_com_spring_java8_nativefunction_test2_Printf1
#define _Included_com_spring_java8_nativefunction_test2_Printf1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spring_java8_nativefunction_test2_Printf1
 * Method:    print
 * Signature: (IID)I
 */
JNIEXPORT jint JNICALL Java_com_spring_java8_nativefunction_test2_Printf1_print
  (JNIEnv *, jclass, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
