/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spring_java8_nativefunction_test3_Printf2 */

#ifndef _Included_com_spring_java8_nativefunction_test3_Printf2
#define _Included_com_spring_java8_nativefunction_test3_Printf2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spring_java8_nativefunction_test3_Printf2
 * Method:    sprint
 * Signature: (Ljava/lang/String;D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_spring_java8_nativefunction_test3_Printf2_sprint
  (JNIEnv *, jclass, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
